version: '3.4'

services:
  companydb:
    container_name: companydb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  stockdb:
    container_name: stockdb
    environment:
        SA_PASSWORD: "pass@word1"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  company.api:
    container_name: company.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://companydb:27017"
    depends_on:
      - companydb
    ports:
      - "8000:80"

  stock.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:StockConnectionString=Server=stockdb;Database=StockDb;User Id=sa;Password=pass@word1"
    depends_on:
        - stockdb
    ports:
        - "8001:80"

