version: '3.4'

services:
  companydb:
    container_name: companydb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  stockdb:
    container_name: stockdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  company.api:
    container_name: company.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://companydb:27017"
    depends_on:
      - companydb
    ports:
      - "8000:80"
